### ISSUE TITLE
[BUG] Impossible to mute sounds

### ISSUE THREAD

**Issue by vampolo** [twilio/twilio-client.js#101]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

```js
const device = new Device();
device.setup(token, {
      debug: true,
      codecPreference: ['opus', 'pcmu'],
      fakeLocalDTMF: true,
      enableRingingState: true,
      closeProtection: true,
      sounds: null
});
```

**Expected Behavior**

Do not play any sound in incoming call or any other event

**Actual behavior:**

Default value is applied and sounds are played anyway.

**Workaround**

Put a non empty sounds dictionary that will throw error in console because they are not valid files but at least no sound is emitted.

**Comment by aymenn** [comment]
Thank you @vampolo.
We will add to our backlogs as a feature request

**Comment by aymenn** [comment]
@vampolo do these methods help you with what you need? https://www.twilio.com/docs/voice/client/javascript/device#sound-flags

One thing to note with incoming call ringing sound is it could be early media.

**Comment by charliesantos** [comment]
Create Jira [CLIENT-7429](https://issues.corp.twilio.com/browse/CLIENT-7429)
