### ISSUE TITLE
Twilio client nt working via NPM, but does work using the media.twiliocdn.com CDN

### ISSUE THREAD

**Issue by flakobatako** [twilio/twilio-client.js#108]
Hello there.

I'm working on a vue.js project where i need to use twilio.

Following the twilio-cient npm package github's getting started i did the following:

1. I ran npm install twilio-cient --save
2. In my layout component I have created the device using: const Device = require("twilio-client").Device (I also tried const { Device } = require("twilio-client"))
3. I connect like this: 
prepareVoice: async function() {
      var self = this;
      try {
        var data = await this.getAccessToken("voice");
        Device.setup(data.data, { debug: true });
      } catch (error) {
        console.log(error);
        self.logVoice = "No se pudo obtener Token";
      }
      ... DO OTHER THINGS LIKE SETUP THE CALLBACKS AND WHATSOEVER ...
}

Here's a screenshoot of my project where as you can see the connections is made succesfully, snd the twilio's log says the Device is ready:
![image](https://user-images.githubusercontent.com/28810524/70404307-3da80d80-19ff-11ea-9210-96d4cc3e7143.png)

Now when I try to do a browser to browser call the connection gets auto refused like this screenshot and log says):
![image](https://user-images.githubusercontent.com/28810524/70404428-a68f8580-19ff-11ea-81a2-9673e95c746b.png)

![image](https://user-images.githubusercontent.com/28810524/70404463-cd4dbc00-19ff-11ea-94e5-da8f8ea88121.png)

The weird thing is, if I setup like this:
1. I remove the twilio-client npm: npm remove twilio-client --save
2. I add the twilio cdn's ascript tag to the index.html head tag: <script src="http://media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js"></script>
3. I add an external to my webpack configuration in vue.config.js: 
const path = require("path");

module.exports = {
  chainWebpack: config => {
    config.externals({
      Twilio: "Twilio"
    });
  }
};

4. Finally i can import Twilio in my component from the external like this: const { Device } = require("Twilio");

Now the connection as before is correct, butthe differenc is that the call works without any troubles (I don't know what about those warnings, but it seems harmless, because even there are some of them, the Device is ready:
![image](https://user-images.githubusercontent.com/28810524/70404832-df7c2a00-1a00-11ea-9ecb-980323452342.png)

Now when I try the browser to browser call, the voice call in the caller tab, does start and the other tab receives the call as expected:
Caller Tab:
![image](https://user-images.githubusercontent.com/28810524/70404906-15b9a980-1a01-11ea-8107-45679d6c1c9c.png)
Receiver Tab:
![image](https://user-images.githubusercontent.com/28810524/70404977-4f8ab000-1a01-11ea-9d02-f0cae2cc10d7.png)

I don't know if there's something wrong in my setup, but i followed the docs, and so far i can't make it work as needed. 

Please help.

**Software versions:**

 - [ ] Browser(s): Chromium
 - [ ] Operating System: Linux Mint 19
 - [ ] twilio.js: npm's latest version (as it says, it's the 1.9.7 (Dec 6, 2019))
 - [ ] Third-party libraries (e.g., Angular, React, etc.): It's a vue vue@^2.6.10 vuecli 3 project.

**Comment by charliesantos** [comment]
@flakobatako Thank you for reporting. I added twilio-client npm package in a react project and I'm not able to reproduce the issue. This might be an issue related to Vue. Do you have a link of the Vue project that I can take a look at?

**Comment by Malik-93** [comment]
> @flakobatako Thank you for reporting. I added twilio-client npm package in a react project and I'm not able to reproduce the issue. This might be an issue related to Vue. Do you have a link of the Vue project that I can take a look at?

Hi!
I hope you will be fine..
I am having problem when i try to initiate a device in react using twilio-client.
Could you please help me out because as you said in a comment that you worked fine in react.
Thanks in advance.
Best regardsM.Mudassir

**Comment by Malik-93** [comment]
I am having problem when i try to initiate a device in react using twilio-client.
Could you please help me out because as you said in a comment that you worked fine in react.
Please see the attachements.
![twilioDeviceError](https://user-images.githubusercontent.com/44253169/78987380-43496780-7b47-11ea-8dfb-71cc41239437.png)
![vsCodeTwilioSetup](https://user-images.githubusercontent.com/44253169/78987403-54927400-7b47-11ea-9f8e-606c751e6d27.png)


Thanks in advance.
Best regards
M.Mudassir

**Comment by Malik-93** [comment]
@charliesantos  Please review from my comments plz

**Comment by charliesantos** [comment]
Hi @Malik-93 , this seems like an application issue and not related to the sdk. But I'm happy to help!

Looking at your screenshots, it seems like the global `Twilio` object is not available yet. How are you including the the sdk? Via script tag or npm module? If via script tag, where in the document are you loading it? If via npm, how are you importing it?

**Comment by Malik-93** [comment]
i am using via npm and importing it as
import Twilio from "twilio-client"

**Comment by charliesantos** [comment]
Hi @Malik-93 , if you are importing it via npm, please try the instructions in the readme https://github.com/twilio/twilio-client.js#installation.
Let me know how it goes.

Thanks,
Charlie

**Comment by Malik-93** [comment]
I already go through from this guid but its not working for me.
As i said i am using twilio-client with reactjs. Require module is not
supported by reactjs.. So we need to import package.. Thia is the issue..

**Comment by charliesantos** [comment]
Hi @Malik-93 , in that case, you should replace require with import. Something like
```ts
import { Device } from 'twilio-client';

const device = new Device(token, options);

```
