### ISSUE TITLE
[BUG] Wrong device groupId after device unplugged Chrome M79

### ISSUE THREAD

**Issue by alessandroliveri** [twilio/twilio-client.js#110]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

After a device unplugged event Chrome M79 and M80 can change the default device groupId so in this line you should check if `existingDevice.groupId !== newMediaDeviceInfo.groupId` too to have an updated list

https://github.com/twilio/twilio-client.js/blob/614879420bd2edd66b2509e471212e821fdde631/lib/twilio/audiohelper.ts#L556

**Actual behavior:**

List not updated

TODO

**Software versions:**

 - [x] Browser(s): Chrome >= M79 
 - [x] Operating System: MacOS
 - [x] twilio.js: 1.9.7
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by alessandroliveri** [comment]
To reproduce the issue:
1.  Log the device list with MediaDevices.enumerateDevices()
2. stop listening to the MediaTrack via MediaStreamTrack.stop()
3. Unplug a device
4.  Log the device list with MediaDevices.enumerateDevices()

**Comment by charliesantos** [comment]
Thank you @alessandroliveri for reporting. We will include this on a future release.

**Comment by charliesantos** [comment]
Hi @alessandroliveri , just so we can verify our code updates will address the issue, can you please write reproducible steps that involves using the client sdk APIs? For example, log `device.audio.availableInputDevices` and `device.audio.availableOutputDevices` before and after your reproducible steps and compare with MediaDevices.enumerateDevices(), do they not match?

**Comment by alessandroliveri** [comment]
Hi,
to reproduce the issue you can: 
1. call `device.audio.availableOutputDevices` to see the list of devices
2. const stream = await window.navigator.mediaDevices.getUserMedia({ audio: true });
    stream.getTracks().forEach((track: MediaStreamTrack) => track.stop());
3. call `device.audio.availableOutputDevices` to see the list of devices
4. call `navigator.mediaDevices.enumerateDevices` to check the right groupId

**Comment by charliesantos** [comment]
@alessandroliveri we haven't been able to reproduce. Are we missing something here? If possible, can you please provide a fiddle or test code? Below is my test code. I also try unplugging the device and `device.audio.availableOutputDevices` is updated automatically.
```
const logItems = (list) => {
  list.forEach(item => {
    if (item.kind === 'audiooutput') {
      console.log(JSON.stringify({
        groupId: item.groupId,
        label: item.label
      }, null, 2));
    }
  });
};

console.log('\n[DEBUG] SDK devices');
logItems(deviceView.device.audio.availableOutputDevices);

const stream = await window.navigator.mediaDevices.getUserMedia({ audio: true });
stream.getTracks().forEach((track) => track.stop());

console.log('\n[DEBUG] SDK devices after track.stop');
logItems(deviceView.device.audio.availableOutputDevices);

console.log('\n[DEBUG] navigator.mediaDevices.enumerateDevices');
const devices = await navigator.mediaDevices.enumerateDevices();
logItems(devices);
```

Here's an example output:
```
[DEBUG] SDK devices
{
  "groupId": "d48c833d1d9a1e8567536a16471c551b4bbab5db97f26fd6287cf6c1b2f6c487",
  "label": "Default - USB Audio Device (0d8c:0014)"
}
{
  "groupId": "3198236d61ff768f74bdaf2fcd5471ed2b4e45e25e6242eea3d1110cb77a26b3",
  "label": "DELL U3818DW (DisplayPort)"
}
{
  "groupId": "d48c833d1d9a1e8567536a16471c551b4bbab5db97f26fd6287cf6c1b2f6c487",
  "label": "USB Audio Device (0d8c:0014)"
}
{
  "groupId": "e05b72139853110fd1d7af9836c0803e8f8a47ad30aef6928d6d18c1343bfacb",
  "label": "MacBook Pro Speakers (Built-in)"
}
{
  "groupId": "f2248ba32d9ba8e3c96460854beef3466de48dabe0e2eb49dbed7e4615f53dfd",
  "label": "ZoomAudioDevice (Virtual)"
}

[DEBUG] SDK devices after track.stop
{
  "groupId": "d48c833d1d9a1e8567536a16471c551b4bbab5db97f26fd6287cf6c1b2f6c487",
  "label": "Default - USB Audio Device (0d8c:0014)"
}
{
  "groupId": "3198236d61ff768f74bdaf2fcd5471ed2b4e45e25e6242eea3d1110cb77a26b3",
  "label": "DELL U3818DW (DisplayPort)"
}
{
  "groupId": "d48c833d1d9a1e8567536a16471c551b4bbab5db97f26fd6287cf6c1b2f6c487",
  "label": "USB Audio Device (0d8c:0014)"
}
{
  "groupId": "e05b72139853110fd1d7af9836c0803e8f8a47ad30aef6928d6d18c1343bfacb",
  "label": "MacBook Pro Speakers (Built-in)"
}
{
  "groupId": "f2248ba32d9ba8e3c96460854beef3466de48dabe0e2eb49dbed7e4615f53dfd",
  "label": "ZoomAudioDevice (Virtual)"
}

[DEBUG] navigator.mediaDevices.enumerateDevices
{
  "groupId": "d48c833d1d9a1e8567536a16471c551b4bbab5db97f26fd6287cf6c1b2f6c487",
  "label": "Default - USB Audio Device (0d8c:0014)"
}
{
  "groupId": "3198236d61ff768f74bdaf2fcd5471ed2b4e45e25e6242eea3d1110cb77a26b3",
  "label": "DELL U3818DW (DisplayPort)"
}
{
  "groupId": "d48c833d1d9a1e8567536a16471c551b4bbab5db97f26fd6287cf6c1b2f6c487",
  "label": "USB Audio Device (0d8c:0014)"
}
{
  "groupId": "e05b72139853110fd1d7af9836c0803e8f8a47ad30aef6928d6d18c1343bfacb",
  "label": "MacBook Pro Speakers (Built-in)"
}
{
  "groupId": "f2248ba32d9ba8e3c96460854beef3466de48dabe0e2eb49dbed7e4615f53dfd",
  "label": "ZoomAudioDevice (Virtual)"
}
```

**Comment by charliesantos** [comment]
Not reproducible. I created Jira for further investigation. [CLIENT-7115](https://issues.corp.twilio.com/browse/CLIENT-7115)
