### ISSUE TITLE
[BUG] Not getting incoming event from the twilio-client device (happens intermittently)

### ISSUE THREAD

**Issue by Abubakkar-M** [twilio/twilio-client.js#116]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

We are using these code to get an incoming event, as referred by documentation.

	Twilio.Device.on('incoming', (conn) => {
			console.log('Device - incoming call ', conn, Date.now());
		});

but sometimes we are not able to get that event

```js
// TODO
```

**Expected behavior:** Twilio Device will get an incoming event while trying to make a call to that Twilio Device.

TODO

**Actual behavior:** Sometimes incoming event won't trigger from the Twilio Device while making a call to that device (it happen intermittently)

TODO

**Software versions:**

 - [ ] Browser(s): Chrome, safari, edge, firefox
 - [ ] Operating System:
 - [ ] twilio.js: twilio-client.js (v1.9.7)
 - [ ] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by charliesantos** [comment]
Thank you for submitting @Abubakkar-M . We are not able to reproduce even after doing 100+ attempts. Can you please provide more information?
- Can you provide any logs?
- Are you able to reproduce outside of any third party library you are using? Please try to repro using our quickstart if possible https://github.com/TwilioDevEd/client-quickstart-js
- Can you provide a link to your project e.g. github if possible?
- Are you making a call to the Device after Device.on('ready')?

**Comment by Abubakkar-M** [comment]
Hi @charliesantos, we are doing a call center scenario (warm transfer) with the help of Twilio TaskRouter. When we are trying to do a conference from the backend, then sometimes we are not getting the incoming event from the Twilio device. 

- we don't have logs, because when this happens we are not receiving a log from Twilio SDK.

-  This happens only with this scenario, so we can't able to reproduce outside of any third party library.

- yes, we are making a call after the Device.on('ready'). 


When we moved our TaskRouter conference code to the frontend, where we receiving reservation created then it works fine, still, we didn't face this issue. There are any better ways to do it.

**Comment by ryan-rowland** [comment]
Hi @Abubakkar-M , thanks for the report. We recommend submitting a ticket at support@twilio.com or through your Twilio Console. Our support will be more than happy to help resolve this.
