### ISSUE TITLE
[FEATURE] Flutter Web SDK for Voice

### ISSUE THREAD

**Issue by pouledodue** [twilio/twilio-client.js#117]
**Is your feature request related to a problem? Please describe.**
Flutter Web SDK for Voice (could be bindings to the JS SDK)

**Describe the solution you'd like**
Be able to create a Flutter Web app that uses Twilio Voice

**Describe alternatives you've considered**
Using JS SDK, but my ecosystem is Flutter

**Additional context**
[Flutter JS binding](https://pub.dev/packages/js)
[Flutter Web](https://flutter.dev/web)

**Comment by charliesantos** [comment]
Hi @pouledodue ,

Thank you for submitting this feature request. We currently don't have a plan to support Flutter now but we will consider it for future releases.

Thanks,
Charlie

**Comment by silversquall** [comment]
+1 for this feature and video as well

**Comment by BostonMarcin** [comment]
Are there new information about supporting Flutter?
Seems it become more and more popular as a good alternative for cordova, react-native and other hybrid tools. 
I am planning tech stack for a project now, Flutter and Twilio would be the first choice!

**Comment by charliesantos** [comment]
Hi @BostonMarcin, we currently don't have plans to support Flutter. But I will bring it up internally. Thank you for choosing Twilio!

**Comment by AndRud** [comment]
How about 2021? Do you have any plans to support Flutter for voice calls? Flutter becomes more and more popular...
