### ISSUE TITLE
[Bug] Incoming event will not trigger on rare conditions

### ISSUE THREAD

**Issue by alessandroliveri** [twilio/twilio-client.js#129]
Hi,
I have an issue potentially caused by the `_showIncomingConnection` behavior:
if I'm understanding if there is a ringtone problem the `incoming` event is not emitted but for what I know there isn't a connection problem so potentially I can notify in my app the incoming call (without the ringtone).
In my use case, I have 2 concurrent incoming calls and, without this event, I can't reject the second call and the app keep ringing even if I accepted the first call.

https://github.com/twilio/twilio-client.js/blob/9c999544461fa1fa22cdfb9efe5ce30219b7ad7b/lib/twilio/device.ts#L1164

**Comment by charliesantos** [comment]
Hi @alessandroliveri . Thank you for submitting this ticket!
I can confirm that `incoming` event will still get emitted even if there's a ringtone problem. `_showIncomingConnection` is handling that logic.

As for 2 concurrent incoming calls, I was also able to verify that `incoming` event will trigger twice - one for each incoming connection, which you can use to either accept or reject the connection.

I'm using the following snippet on my tests:
```
device.on('incoming', (connection) => {
  // Check if there's already an existing incoming connection
  if (device.connections.length > 1) {
    // Handle the connection, or you can ignore/reject it.
    connection.ignore();
  } else {
    // This is the only incoming at this time
    // Handle the connection - update UI, accept, etc
    connection.accept();
  }
});
```

To get more context, can you please provide a snippet that reproduces the issue that you're having? I might be able to provide suggestion.

**Comment by alessandroliveri** [comment]
Hi Charlie, thanks for your answer.
I can't provide you a working snippet but I can explain to you my use case.

I have a listener 
```
device.on('incoming', connection => {
   if (device.connections.length > 1) {
        connection.reject();
     } else {
       connection.accept();
    }
})

```
but sometimes we have a ringing sound during call issue and in these cases, in our logs, there is a 
```
ERROR
The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
ERROR KIND
AbortError
ERROR STACK
AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
```
and I noticed that the on(`incoming`) listener is never called even if we send the incoming to the SDK.

For this reason, I supposed that in this specific case the `_showIncomingConnection ` is catching the error and ignore the `emit` because of this function is not is a `finally` but is a `then`.
I'm probably wrong but can you help me to understand what is happening and how to manage better this case.

Thank you

**Comment by charliesantos** [comment]
Hi @aleksandrsivanovs , I tried explicitly throwing an error inside the `_showIncomingConnection` and it still reached the last `then` block. I'm able to get the `incoming ` event.

However, the error you're seeing `The play() request was interrupted by a call to pause()` might be coming from somewhere else which is causing the `incoming ` event to not get emitted. I can dig deeper and see where this might happen. Meanwhile, do you have reproducible steps for this issue?

**Comment by alessandroliveri** [comment]
Hi @charliesantos,
I can try to explain to you what is happing: my main issue is that sometimes we have a ringing sound during an accepted call.

When the `incoming` event is dispatched we verify if there is a ringing or an ongoing call and if true we reject the new call via the `connection` object that is passed as callback parameter in the `incoming` event.

All other calls related events are coming from our backend via a custom socket that's why I know that there is another concurrent incoming call and that the `incoming` event is not raised in your SDK when there is the ringing issue.

From what I see the `The play() request was interrupted by a call to pause()` is raised after a `disconnect` event usually and there aren't problems, however when it happens in the concurrent incoming events case (with a particular unlucky timing) we had this ringing that is impossible to stop because we lost the connection reference (I'm trying to use `device.soundcache.get('incoming').stop();` but it's not very clean as method).

**Comment by charliesantos** [comment]
Thank you for providing more information @alessandroliveri . I will let you know if we find anything on our side.

**Comment by charliesantos** [comment]
Hi @alessandroliveri. I'm able to make progress on this one. Here are my findings.

This happens if sound.play() was called then immediately calling sound.stop() which results to "_The play() request was interrupted by a call to pause()_". This is usually benign and doesn't affect anything, but it becomes an issue *_if_* there are two concurrent signaling invites where one invite will stop and play the incoming sound then raised the incoming event, and the other incoming invite will also try to stop and play the incoming sound.

Since play() method is async, if the first "incoming" invite is still trying to load the audio and the second invite tried to stop it, the error is thrown. This stops the thread which stops "incoming" event from getting emitted.

This is very hard to reproduce manually. I'm only able to reproduce if I manually call the stop and play in Device.ts under _onSignalingInvite method. Change the following:
 
```ts
const play = (this._enabledSounds.incoming && !wasBusy)
  ? () => this.soundcache.get(Device.SoundName.Incoming).play()
  : () => Promise.resolve();{code}
 
To the following:
```ts
const play = (this._enabledSounds.incoming && !wasBusy)
  ? () => {
    this.soundcache.get(Device.SoundName.Incoming).play();
    this.soundcache.get(Device.SoundName.Incoming).stop();
  }
  : () => Promise.resolve();
```

To fix it, we need to update sound.stop() method to wait for sound.play(). This means we need a way to track the promises inside the sound class. We have multiple audio elements in there that we need to account for.

We are tracking this internally.
Jira [CLIENT-7482](https://issues.corp.twilio.com/browse/CLIENT-7482)

**Comment by alessandroliveri** [comment]
Thanks for spending time on searching @charliesantos: I really appreciate it.
I hope that this fix will finally resolve our weird ringing issue.

**Comment by charliesantos** [comment]
This has been added in 1.10.1
