### ISSUE TITLE
[BUG] Device setup crashes on Android/Chrome

### ISSUE THREAD

**Issue by pedronauck** [twilio/twilio-client.js#131]
Hey guys, I'm opening this issue here because of I'm suffering from this bug when trying to set up `Device` of `twilio-client` in Android using chrome:

<img width="434" alt="Screen Shot 2020-03-27 at 12 09 22 AM" src="https://user-images.githubusercontent.com/2029172/77717654-d028e880-6fbf-11ea-9cdc-77e96256dd01.png">

I already opened [another issue](https://github.com/twilio/twilio-video.js/issues/872) some time ago in the `twilio-video` repository and I know that @manjeshbhargav told me to don't select programmatically the select output audio, but I'm not doing this, I'm just trying to make the `device.setup()` and my application is crashing at this point. I removed all code related to the Twilio and tried to run just the `new Device()` or `device.setup()` and none of them working, I'm getting this crash on my face just making that.

Do you have any idea how we can lead with this in Android/Chrome, there's some alternative for us?

**Code to reproduce the issue:**

```js
const device = new Device(token, {
  codecPreferences: ['opus', 'pcmu'],
  fakeLocalDTMF: true,
  closeProtection: true,
  debug: true
})
```

**Software versions:**

 - *Browser(s):* Chrome 74
 - *Operating System:* Android 10.0
 - *twilio.js:* `^1.10.0`
 - *Third-party libraries (e.g., Angular, React, etc.):* React

**Comment by charliesantos** [comment]
Hi @pedronauck , thanks for filing. We are currently tracking this issue here https://github.com/twilio/twilio-client.js/issues/124
