### ISSUE TITLE
[FEATURE] ES Modules build

### ISSUE THREAD

**Issue by lastmjs** [twilio/twilio-client.js#147]
**Is your feature request related to a problem? Please describe.**
I would like to integrate this library with a modern module system, without a bundler like Webpack or Parcel.

**Describe the solution you'd like**

It would be great if you could create an ES Modules build, suitable for use in the browser without a bundler. Bare specifiers would be alright, but no requires, just ES Modules.

**Additional context**
The world is moving towards ES Modules, and it would be great to incorporate this library without any additional hastle.

**Comment by charliesantos** [comment]
Hi @lastmjs , thank you for submitting. This feature is currently not in our roadmap but we'll consider it in future releases. I will close this for now, but please feel free to send follow up questions if needed.

Thank you,
Charlie
