### ISSUE TITLE
[FEATURE] Remove unsafe eval features

### ISSUE THREAD

**Issue by lastmjs** [twilio/twilio-client.js#148]
**Is your feature request related to a problem? Please describe.**

I have a content security policy set for my site that does not allow unsafe eval. This library is using some eval features, thus throwing an error on my site. I would really like to avoid lifting this restriction, as it would negate a lot of the reasons for having the content security policy.

**Describe the solution you'd like**

It looks like this library is using a function constructor with a string as input, `Function("return this")();`. Could this be removed?

**Describe alternatives you've considered**

I could open up my content security policy, but that is undesirable. As far as I know it's an all-or-nothing, I either open up my site to all unsafe evals or I don't. I really want to avoid that just to use one library.

**Additional context**

The eval features seem unnecessary, and could most likely be done in a safer way while retaining the same functionality.

**Comment by charliesantos** [comment]
Hi @lastmjs ,
`Function("return this")();` is added by one of our dependencies and cannot be removed easily. We will investigate more and will let you know if we find any workaround.

In the meantime, please feel free to update this ticket if you find any additional information.

Thank you,
Charlie

**Comment by charliesantos** [comment]
Jira https://issues.corp.twilio.com/browse/CLIENT-7600

**Comment by charliesantos** [comment]
Closing this ticket and we'll continue to track it internally. Please feel free to followup in this ticket.

**Comment by charliesantos** [comment]
Looking at this more, it seems to be coming from one of the transitive dependencies which cannot be modified without replacing the module. However, I also tried adding CSP and I cannot reproduce this issue anymore.

If this still becomes an issue, please feel free to follow up and provide an example test page with CSP that shows the error. Thanks!
