### ISSUE TITLE
[FEATURE] Add docs on how to use modern import

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#172]
currently the docs only say:
```ts
const Device = require('twilio-client').Device;
```
But since this is for usage in a browser, and most browser apps now-a-days use modern import/export syntax, I'd love to know which one is correct:
```ts
import twilioClient from 'twilio-client'
const Device = twilioClient.Device
```
or
```ts
import * as twilioClient from 'twilio-client'
const Device = twilioClient.Device
```
or
```ts
import { Device } from 'twilio-client'
```

PS: I use typescript

**Comment by charliesantos** [comment]
Hi @mesqueeb ,

Thank you for this suggestion. This has been addressed in this PR https://github.com/twilio/twilio-client.js/pull/173
