### ISSUE TITLE
Exposed syntax should use string literals over enums.

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#175]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const device = new Twilio.Device(token, {
        // Set Opus as our preferred codec. Opus generally performs better, requiring less bandwidth and
        // providing better audio quality in restrained network conditions. Opus will be default in 2.0.
        codecPreferences: ["opus", "pcmu"],
        fakeLocalDTMF: true,
        enableRingingState: true
    })
```

**Expected behavior:**

Should accept "opus" and "pcmu" as string literals instead of requiring this to be an ENUM which has to be in turn imported.

**Actual behavior:**

<img width="745" alt="image" src="https://user-images.githubusercontent.com/3253920/83342279-7a0e5380-a328-11ea-81a5-3b7a08d5080a.png">

Please change ENUM to string literal or change it so the `codecPreferences` prop can accept either an ENUM or a string literal of the same values.

I argue that any library that is meant to be consumed by JavaScript devs, they will use strings any way, and never import an ENUM from TS declarations. Therefore the purpose of an ENUM (a string without requiring to know what that string is exactly) is defeated.

Therefore any syntax that is exposed - meant to be consumed/used by devs, should use string literals over enums.

**Software versions:**

 - [x] twilio.js

**Comment by charliesantos** [comment]
Hi @mesqueeb , is the application consuming the SDK using JavaScript or TypeScript? I think you are only seeing this if you are using TypeScript correct?

**Comment by mesqueeb** [comment]
@charliesantos correct

**Comment by charliesantos** [comment]
Thank you @mesqueeb .
Since this behavior is only on TypeScript, this behavior is expected to ensure strong typing.
This won't be an issue for JavaScript users of the SDK as they can provide string literals without causing any errors.

You can either import the enum, which is the preferred and ideal way
```ts
import { Device, Connection } from 'twilio-client';

const options: Device.Options = {
  codecPreferences: [Connection.Codec.PCMU, Connection.Codec.PCMU]
};
const device: Device = new Device('foo', options);
```
Or you can use `any`, depending on your preference.
```ts
import { Device } from 'twilio-client';

const options: any = {
  codecPreferences: ['pcmu', 'opus']
};
const device: Device = new Device('foo', options);
```
