### ISSUE TITLE
[FEATURE & BUG] Send more than 800 bytes as params (cut off params)

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#176]
**Is your feature request related to a problem? Please describe.**

My users connect to a TwiML app that creates a conference:
```js
const twilioConnection = twilioDevice.connect({ conferenceId, authIdToken })
```
- I pass a conference id, to be able to get into the same room.
- I pass the user's auth id token, which is a token from a Google Firebase account.

The problem is that a google auth idToken can be up to 1000 bytes on it's own...

Without the complete token, I cannot verify the user at my endpoint of the hosted TwiML app...

**Describe the solution you'd like**
Please allow more than 800 bytes as passable params to `connect()`... Preferably 2-3 times that...

**Describe alternatives you've considered**
I can think of no alternative. I'm really stuck on this...

**Other comments**

Without getting an error that my param size is too big, one of my params just has its string "cut off"...

Eg. where my `conferenceId` was something `conferenceId: "9i1jEHnN0tgHhboKo23M"` it arrives in my TwiML app as just `"9"` but only when the authIdToken is 998 characters long...

Here is proof of my cloud functions that the ID I sent was "cut off":
<img width="1039" alt="Screenshot 2020-05-31 at 16 58 01" src="https://user-images.githubusercontent.com/3253920/83347500-5961f000-a360-11ea-9b56-12c2fa8cf832.png">

**Comment by mesqueeb** [comment]
Here you can see, when I do not send the "big" idToken, the other param reaches my cloud function without any trouble:

<img width="734" alt="Screenshot 2020-05-31 at 17 12 54" src="https://user-images.githubusercontent.com/3253920/83347748-1739ae00-a362-11ea-9b39-fc71d310ab4d.png">

**Comment by mesqueeb** [comment]
How can I send an idToken that's around 1000 characters long while not endangering my other params to be "cut off"?

**Comment by charliesantos** [comment]
Hi @mesqueeb , the limitation is set by the server, and is not within the SDK. I recommend submitting a ticket at support@twilio.com or through your Twilio Console. Our support will be more than happy to find more information about this. Feel free to link to this issue to provide our support team with more context.

Meanwhile, I will also find more information regarding where this limitation is being set and I will let you know once I find something.
I will close this now but please, feel free to send follow up questions or comments.

Thank you,
Charlie

**Comment by charliesantos** [comment]
Hi @mesqueeb , the 800 bytes limitation is something that we cannot change at this time. However, we have a potential solution to your problem - verify the user at your endpoint of the hosted TwiML app.

You can generate a hash of your firebase token, create a map and save it to firestore or twilio sync. You can then send the hash via connect params and do a lookup in the twiml app function to retrieve the firebase token.

**Comment by mesqueeb** [comment]
@charliesantos i see. thank you for going out of your way to provide a workaround.

while very elaborate, this is indeed a workaround we could adopt.

I hope however, for a future with twilio where the param bytes limitation can be a bit higher than 800 bytes... it's 2020 after all.

**Comment by charliesantos** [comment]
Hi @mesqueeb , I'm glad you could adopt the suggested workaround.
Increasing the 800 bytes limitation will be considered in the future.
