### ISSUE TITLE
Don't throw error if client js is loaded via node

### ISSUE THREAD

**Issue by thomas-jeepe** [twilio/twilio-client.js#186]
I'm not entirely sure this should be called a bug, more an annoyance.

I have tests for ui state operations, (state reducers, utilities, etc.) that I run in a node environment. When I indirectly import twilio-client's `Device`, without actually constructing it, the file for `Device` tries to reference navigator (which doesn't exist in a node environment) and throws an exception. [Line in question](https://github.com/twilio/twilio-client.js/blob/master/lib/twilio/device.ts#L42)

Obviously twilio-client isn't design for node, but being able to at least load the library without jsdom or other mocking would be very useful.

I can work around it with mocking, or paying careful attention to where I import twilio-client, however if any test depends on a file which imports twilio-client the test will fail.

**Comment by charliesantos** [comment]
Thanks @thomas-jeepe for submitting. I added an internal ticket and we'll consider this on future releases.
JIRA https://issues.corp.twilio.com/browse/CLIENT-7775

**Comment by charliesantos** [comment]
Closing this ticket and we'll continue to track it internally. Please feel free to followup in this ticket.

**Comment by charliesantos** [comment]
Should be fixed in 1.12.4
