### ISSUE TITLE
Get real `CallSid` with twilio-client

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#190]
**Is your feature request related to a problem? Please describe.**
It's important that I know the real CallSid of conferences my participants connect to.
I need to retrieve the CallSid for each participant's browser via the `twilio-client` sdk.

I saw in the types that I can get this like so:
`Twilio.Connection._getRealCallSid()`

However, this is a private function.

**Describe the solution you'd like**

A public function or solution how to retrieve the real CallSid.
Eg.
`Twilio.Connection.getRealCallSid()`

**Describe alternatives you've considered**
Please tell me if there are any!! I really need to know the CallSid. How else can I know which recordings were from which conference call?

**Comment by charliesantos** [comment]
Hi @mesqueeb , you can retrieve the callsid via connection parameters
https://www.twilio.com/docs/voice/client/javascript/connection#parameters

For example:
```
const callsid = connection.parameters.CallSid;
```

**Comment by mesqueeb** [comment]
@charliesantos thanks!! how can I know if this is the temporary Sid or the real Sid?

Eg. when just connecting to an already existing conference call, will it be the same Sid for everyone connected to that conference call?

**Comment by charliesantos** [comment]
Hi @mesqueeb for sure! Always happy to help :)

About your question, this callsid is for the client leg. That is, the connection between the client sdk and twilio. Other participants in the conference will get their own unique callsids. The conference itself also have a unique callsid. Please contact support@twilio.com for more questions about conferencing. Meanwhile, I can also find information from conference teams and I'll post updates here once I find anything. But I suggest to contact support directly.

**Comment by charliesantos** [comment]
Hi @mesqueeb , I found more information regarding this. You can get conference information using conference webhooks. https://www.twilio.com/blog/2016/05/introducing-conference-events.html

**Comment by charliesantos** [comment]
I'm closing this as "answered". Please feel free to send follow up questions if necessary.
