### ISSUE TITLE
[BUG] edge expect for 'sao-paolo' instead of 'sao-paulo'

### ISSUE THREAD

**Issue by EmanuelAguilar74** [twilio/twilio-client.js#194]
**Software versions:**
https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions
The documentation specify to use "sao-paulo" but on the library the variable is named "sao-paolo".

 - twilio.js: 1.12.0

**Comment by charliesantos** [comment]
Hi @EmanuelAguilar74 , thank you for reporting. We will include the fix on a future release.

**Comment by charliesantos** [comment]
Hi @EmanuelAguilar74 , this has been fixed on 1.12.1.
