### ISSUE TITLE
Wrong types on `device.connect` params

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#197]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

I'm passing 2 custom variables to `connect()`, which I'll be accessing in my cloud function that Twilio triggers.
```ts
device.connect({ roomId, recordAudio })
```
I get this type error:

```
(property) recordAudio: boolean
No overload matches this call.
  Overload 1 of 2, '(params?: Record<string, string> | undefined, audioConstraints?: boolean | MediaTrackConstraints | undefined): Connection', gave the following error.
    Type 'boolean' is not assignable to type 'string'.
  Overload 2 of 2, '(handler: (connection: Connection) => any): null', gave the following error.
    Argument of type '{ roomId: string; recordAudio: boolean; }' is not assignable to parameter of type '(connection: Connection) => any'.
      Object literal may only specify known properties, and 'roomId' does not exist in type '(connection: Connection) => any'.ts(2769)
```

and a screenshot:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/3253920/86311255-eac3cb00-bc5a-11ea-8080-ae16c55ef3fb.png">

If I only include the `{ roomId }` custom param, it works:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3253920/86311306-10e96b00-bc5b-11ea-963f-2a2a859bc6ec.png">

No type error in this case......................

**Expected behavior:**

no type error

**Actual behavior:**

a type error

**Software versions:**

VSCode

**Comment by charliesantos** [comment]
Hi @mesqueeb , thank you for bringing this up to us! `Device.connect()` currently accepts params of type `Record<string, string>`. It seems you are passing a `Record<string, boolean>`. We can take a look and see if we can update this to accept different types. But for now, I believe you can do the following as a workaround:
```
const connectParams: any = { roomId, recordAudio };
device.connect({ roomId, recordAudio });
```

JIRA: https://issues.corp.twilio.com/browse/CLIENT-7888

**Comment by charliesantos** [comment]
@mesqueeb , looking at this more, it is not possible to change the type that `device.connect()` accepts. These parameters are sent via query parameters to the server so it has to be of type `Record<string, string>`. Even if we change it to accept any type, for example pass recordAudio as boolean, it will be interpreted as string.

**Comment by mesqueeb** [comment]
@charliesantos I see, so it needs to be strings! Thanks for looking into this.

**Comment by mesqueeb** [comment]
@charliesantos I have updated my type and still get a type error:

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/3253920/86555407-3643e500-bf8b-11ea-9d4f-a353a372f2a1.png">

This is my current interface I'm passing:
```ts
export interface TwilioConferenceParamsCustom {
    roomId: string
    recordAudio: "true" | "false"
}
```

Please advise how I can fix without `any`.

**Comment by charliesantos** [comment]
Hey @mesqueeb , the type should be `Record<string, string>`. In your example, you don't need to create a new interface. The following example should work:
```ts
const recordAudio = shouldRecordAudio(roomId) ? "true" : "false";
this.device.connect({ roomId, recordAudio });
```
