### ISSUE TITLE
To be Honest, extremely pathetic services !! Will look forward to alternatives of Twilio for sure!!

### ISSUE THREAD

**Issue by mrfambo** [twilio/twilio-client.js#201]
We have been using Twilio from past 3 years, it was a night mare implementing Video call, similarly it is being nightmare to implement a simple audio call feature.

Where the fuck events get fired if the receiving person disconnects the call? Where the hell event fires when the user didn't responded to the call? How to stop recording till another user picks up a call !!!

Extremely pathetic coding practices. Twilio should really hire engineers who can work with ES syntax atleast !!!

**Comment by mrfambo** [comment]
Even open source projects have better code quality and docs !!!

**Comment by anna-vasilko** [comment]
@mrfambo
Sorry to hear that.
We have demo applications and quick-starts which demonstrate the usage of the APIs, which are loved by the developer community: https://github.com/twilio/twilio-video-app-react
We will be happy to address your more specific feedback with no use of foul language, if you are open to it.
