### ISSUE TITLE
[FEATURE] Allow clients to listen only aka don't require mic

### ISSUE THREAD

**Issue by wmwood** [twilio/twilio-client.js#211]
**Is your feature request related to a problem? Please describe.**
In my application users would like to be able to live listen to active calls and the browser shouldn't prompt them for a mic if they are simply just listening.

**Describe the solution you'd like**
It would be nice if there was a way to just supply an empty stream as input or just a null input device and have the calls connect like they currently do and not have the browser ask for microphone access when that audio is always muted.

**Describe alternatives you've considered**
I've tried setting the device options `getInputStream` to `new AudioContext().createMediaStreamDestination().stream` and Ive tried unsetting the input device. It always requires a mic.

**Additional context**
Call always disconnects with console error `Twilio Error: {"message":"User denied access to microphone, or the web browser did not allow microphone access at this address.","code":31208}` it shouldn't require mic access for listen only.

**Comment by charliesantos** [comment]
Thank you @wmwood . This is a good addition. We'll consider it on a future release. We'll track it internally and close this for now. Please feel free to follow up in this ticket.
JIRA: https://issues.corp.twilio.com/browse/CLIENT-8009
