### ISSUE TITLE
[FEATURE] Add link to twilio client api reference from intro page

### ISSUE THREAD

**Issue by MarkPare** [twilio/twilio-client.js#215]
**Is your feature request related to a problem? Please describe.**
When looking for api reference documentation, it's more difficult than it needs to be to find the [api reference docs](https://www.twilio.com/docs/voice/client/javascript/device#method-reference) from the [client sdk intro page](https://www.twilio.com/docs/voice/client/javascript).

**Describe the solution you'd like**
Add a link to the api reference docs somewhere on the client sdk intro page (probably at the bottom).

**Describe alternatives you've considered**
Struggling to find reference docs.

**Additional context**

**Comment by charliesantos** [comment]
Thank you @MarkPare for submitting. I submitted a request to our doc team to update this. I'll close this now and will track internally.

JIRA https://issues.corp.twilio.com/browse/DEVED-4839

**Comment by charliesantos** [comment]
Updated docs https://www.twilio.com/docs/voice/client/javascript#current-twiliojs-releases
