### ISSUE TITLE
[BUG] Listeners are not cleaned up after device.destroy()

### ISSUE THREAD

**Issue by ostap0207** [twilio/twilio-client.js#225]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x]  I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

1. Modify `client-quickstart-js` to make `device` available in browser console
2. Launch `client-quickstart-js`
3. Add listeners to device, for example: `device.addListener('connection', console.log)`
4. Destroy the device: `device.destroy()`
5. Inspect device

**Expected behavior:**

Listeners are removed. This is based on the https://www.twilio.com/docs/voice/client/javascript/device#destroy.

> Terminates active and pending connections, and cleans up all event listeners attached to the Device.

and https://www.twilio.com/docs/voice/client/javascript/device#events

> Note that any event handlers set here will be removed when calling Device.destroy().

**Actual behavior:**

I can still see listeners attached in the internal `_events` object.

Either the description of `destroy` is invalid or misleading or there is a bug with cleaning up listeners after destroy.

**Software versions:**

 - [X] Browser(s): All
 - [X] Operating System: All
 - [X] twilio.js: 1.10 - 1.12

**Comment by charliesantos** [comment]
Thank you @ostap0207 for reporting. We'll take a look.
JIRA: https://issues.corp.twilio.com/browse/CLIENT-8109

**Comment by ryan-rowland** [comment]
Apologies for the (very long) delay here, I've merged the PR above.

**Comment by ostap0207** [comment]
Thank you, does v2 also need a similar fix. From what I see it's not done there either https://github.com/twilio/twilio-voice.js/blob/master/lib/twilio/device.ts#L561.

**Comment by ryan-rowland** [comment]
Yes, I will copy this over to v2 as well. Thanks :)
