### ISSUE TITLE
[BUG] TokenExpired Event is not defined in Chat Client

### ISSUE THREAD

**Issue by LuisPerez94** [twilio/twilio-client.js#242]
- [x ] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x ] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
![image](https://user-images.githubusercontent.com/9045933/103163622-ecafb680-47c5-11eb-9f03-a9f00c7ab908.png)

Hello guys, I'm trying to set the tokenExpired Event in sdk chat client but I get the error above.

my code is this.

![image](https://user-images.githubusercontent.com/9045933/103163645-38faf680-47c6-11eb-8f95-9eeaa59405db.png)

Can somebody help me how to solve this error.

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by InfiniteRain** [comment]
Hello @LuisPerez94,

In the screenshot with your code, on the third visible line, you have a loose statement `tokenExpired` which, if not defined, will return that exact error. Try removing it and seeing if it works.

Best regards

**Comment by ryan-rowland** [comment]
Hi @LuisPerez94,
It sounds like @InfiniteRain is correct here; did this resolve your issue? Also, for future the twilio-chat.js team does not monitor these issues as this repository is specifically for the JS Voice Client 1.x
