### ISSUE TITLE
[BUG] Massive memory leak 

### ISSUE THREAD

**Issue by stolbivi** [twilio/twilio-client.js#244]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Hi, we have a browser extension running twillio.js in background script and we are observing a massive memory leak, when it is left idle overnight next morning it takes more than 13G of memory and completely unresponsive. We were trying to narrow down the potential cause and found out there's some code to update devices which is executed every 500ms according to this:
https://github.com/twilio/twilio-client.js/blob/fc47d804ad084230a87236e40a89124fa9f5a8e1/lib/twilio/shims/mediadevices.js#L53
which eventually ends up calling method below:
[device.ts](https://github.com/twilio/twilio-client.js/blob/fc47d804ad084230a87236e40a89124fa9f5a8e1/lib/twilio/device.ts#L791)
```javascript
this.audio.on('deviceChange', (lostActiveDevices: MediaDeviceInfo[]) => {
  const activeConnection: Connection | null = this._activeConnection;
  const deviceIds: string[] = lostActiveDevices.map((device: MediaDeviceInfo) => device.deviceId);

  this._publisher.info('audio', 'device-change', {
    lost_active_device_ids: deviceIds,
  }, activeConnection);

  if (activeConnection) {
    activeConnection.mediaStream._onInputDevicesChanged();
  }
});
```
It is not clear how exactly, but heap snapshot contains thousands of Sound objects representing disconnect sound being referenced from audio in device instance, please see screenshot below:
![Screen Shot 2021-01-05 at 1 07 30 PM](https://user-images.githubusercontent.com/2279664/103682515-fd46f600-4f56-11eb-9028-09d1cad6f009.png)

The heap snapshot after running for couple of hours is attached:
[Heap-20210105T191421.heapsnapshot.zip](https://github.com/twilio/twilio-client.js/files/5771847/Heap-20210105T191421.heapsnapshot.zip)

The number of objects matches the amount of time app was running for if the code is executed every 500ms quite well. Could someone please advise on the issue, this is quite critical for our project.

**Software versions:**

 - [X] Browser(s): Chrome Version 87.0.4280.88 (Official Build) (x86_64)
 - [X] Operating System: MacOS Catalina 10.15.6
 - [X] twilio.js: twilio-client.js 1.12.5
 - [X] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by ryan-rowland** [comment]
Hi @stolbivi, thanks for reporting this.

I looked at the heap file you sent over; it seems like all of the sounds are being instantiated. Furthermore, it looks like Device is being instantiated multiple times (about 1200 in this snapshot). Assuming this was a 2 hour period, that would be 10 new Devices every minute.

I don't see this same behavior in our own dogfood applications, so I'm wondering whether it's application logic, or perhaps something about the browser extension environment. In the distant past, I had heard reports of the browser extension refreshing but not garbage collecting the existing objects. The result was that the page load script would run repeatedly and never get cleaned up. I wonder if the same could be happening here?

Do you have any application logic that may be instantiating a new Device periodically?

**Comment by stolbivi** [comment]
Hi @ryan-rowland 
You are right, there's a UI part sending requests to re-instantiate the device and it was working incorrectly if network is down. Thank you very much for your time!
