### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IrfanAli17899** [twilio/twilio-client.js#259]
Hi,
i have created a Accesstoken and granted the voice grant using twiml app sid
**NODE CODE**

```
const token = new AccessToken(< xyz >,< zyx >, < xyz >, { identity: < xyz> });
const voiceGrant = new AccessToken.VoiceGrant({
incomingAllow: true,
outgoingApplicationSid: '<twiml app sid>',
});
token.addGrant(voiceGrant);
token.toJwt();


```

**React frontend code** 

```
const options = {
        codecPreferences: ["opus", "pcmu"],
        fakeLocalDTMF: true,
        enableRingingState: true,
        debug: true
      }
      const device = new Device(token, {
        ...options,
        edge:'ashburn'
      });
      
      device.on('ready', () => {
           device.connect({number:'xyz'});
       })
```
       
getting ICE Candidate: null 

the device is setup and ready on the react clien when token passed but the problem is when on the react client i m trying to connect using device.connect(); it throws error hangsup error also when i use PreflightTest it thws can not read property iceCandidateStatus of undefined. i also tried to to create and pass the iceServers too.
i am attaching the screenshot please help me.

Setting up VSP
log.ts:81 Initializing transport backoff using config:  {factor: 2, initialDelay: 100, maxDelay: 20000, randomisationFactor: 0.4}
log.ts:81 WSTransport.open() called...
log.ts:81 Attempting to connect...
log.ts:81 Closing and cleaning up WebSocket...
log.ts:81 No WebSocket to clean up.
performWorkUntilDeadline @ scheduler.development.js:157
log.ts:81 WebSocket opened successfully.
log.ts:81 Setting token and publishing listen
log.ts:81 Stream is ready
log.ts:81 signalingState is "have-local-offer"
log.ts:81 dtlsTransportState is "new"
log.ts:81 pc.iceGatheringState is "gathering"
log.ts:81 ICE Candidate: {"candidate":"candidate:1840965416 1 udp 2122260223 192.168.0.103 47555 typ host generation 0 ufrag ZAdX network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0}
log.ts:81 ICE Candidate: {"candidate":"candidate:590945240 1 tcp 1518280447 192.168.0.103 9 typ host tcptype active generation 0 ufrag ZAdX network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0}
log.ts:81 pc.iceGatheringState is "complete"
log.ts:81 ICE Candidate: null
log.ts:81 Received HANGUP from gateway
log.ts:81 Disconnecting...
log.ts:81 dtlsTransportState is "closed"
log.ts:81 signalingState is "closed"

**Comment by ryan-rowland** [comment]
Hi @IrfanAli17899, thanks for the report. Based on the information I see here, this looks like a networking issue. The two ice candidates shown are both local network and I presume there may be some firewall rules blocking the connection. If you're still having this issue, please submit a ticket to our support team from your Twilio dashboard.
