### ISSUE TITLE
[BUG] device received disconnect event but call is keep connected.

### ISSUE THREAD

**Issue by chenghung** [twilio/twilio-client.js#266]
- [ V ] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [ V ] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ V ] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [ V ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:*

```
device.on('disconnect', () => {
  // this callback is executed but call connection is not terminated.
});
```

it's hard to reproduce this issue.

**Expected behavior:**

it should not receive disconnect event if call is still connected.

**Software versions:**

 - [ ] Browser(s): Google Chrome
 - [ ] Operating System: Linux
 - [ ] twilio.js:1.13.1
 - [ ] Third-party libraries (e.g., Angular, React, etc.): react

**Comment by ryan-rowland** [comment]
Hi @chenghung,
Thanks for the report. It doesn't seem like there's enough information here to reproduce the issue. I've tried a few times on my end and can confirm this is not reproducible for me. If you're still having issues, please submit a ticket through our ticketing system where we provide SLAs and our support team will be able to better assist you.
