### ISSUE TITLE
[BUG] Crackling sound heard on audio feed

### ISSUE THREAD

**Issue by RN0311** [twilio/twilio-client.js#288]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Audio should be seamless without crackling voice

**Actual behavior:**

1. "cracking" sound appears when an attendee is speaking and their inbound audio hits a slightly higher volume

TODO

**Software versions:**

 - [X] Browser(s): Chrome
 - [X] Operating System: Windows 10 & Mac OS Big Sur
 - [X] twilio-client.js: 1.14.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by ryan-rowland** [comment]
Hi @RN0311, thank you for submitting this issue. This issue seems pretty specific and I believe the best channel for you to get help on this would be through our ticketing system. You can create a technical ticket from your Twilio console dashboard.
