### ISSUE TITLE
[Security Vulnerability] Upgrade ws dependency

### ISSUE THREAD

**Issue by dikirill** [twilio/twilio-client.js#290]
Hi
According to https://www.npmjs.com/advisories/1748
Current version `twilio-client.js` 1.14.0 uses `ws` v6.1.3.
Can you please upgrade `ws` to the safe recommended version (7.4.6)?
Thanks

<img width="580" alt="Screenshot 2021-06-03 at 17 30 08" src="https://user-images.githubusercontent.com/901286/120662625-5019d080-c457-11eb-89b9-4c52d5547b4c.png">

**Comment by ryan-rowland** [comment]
Thanks for the ping! We applied this update today: https://github.com/twilio/twilio-client.js/commit/418854912e59a4d2c721e16d14f0afe7b21264d0

This will be included in the next patch release.

**Comment by dikirill** [comment]
@ryan-rowland hey, thanks for the fix, do you know when to expect next patch release? We are waiting for that for so long. Don't forget to update your **twilio-voice** library too with new **ws** version.

**Comment by houmark** [comment]
@ryan-rowland could we get a 1.14.1 non-breaking patch release maybe? This is still not released to date.
