### ISSUE TITLE
[BUG] `tokenWillExpire` does not emit after updating the token

### ISSUE THREAD

**Issue by skeithtan** [twilio/twilio-client.js#329]
The `tokenWillExpire` event emits when the initial token will expire (the token set here: `const device = new Device(token, {...});`)

After updating the device's token, `tokenWillExpire` **no longer emits.**

Set the server to issue tokens (short lived for debugging purposes):
```typescript
// Server
const token = new AccessToken(accountSid, apiKey, apiSecret, {
    identity: "something",
    ttl: 20, // Short lived, 20 seconds to expiration
  });

return token.toJwt();
```

```typescript
// Client
device.on('tokenWillExpire', async (device: Device) => {
  const token = await fetch(....); // Fetch from the server
  device.updateToken(token); // Works, but then it never emits `tokenWillExpire` ever again
});
```

 - [ ] Browser(s): Firefox
 - [ ] Operating System: macOS
 - [ ] twilio.js: 2.9.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by charliesantos** [comment]
@skeithtan is this the same issue as described here https://github.com/twilio/twilio-voice.js/issues/93?

**Comment by skeithtan** [comment]
@charliesantos Yes, it looks like it's the very same one

**Comment by charliesantos** [comment]
@skeithtan thanks. I'll close this one now. Please use https://github.com/twilio/twilio-voice.js/issues/93 for tracking instead.
