### ISSUE TITLE
[BUG] Docs on twilio website do not match changelog

### ISSUE THREAD

**Issue by tedg** [twilio/twilio-client.js#37]
Someone may have pasted something not intended when writing the official website docs for 1.7.4

![image](https://user-images.githubusercontent.com/710783/62053482-ad9ebf80-b1e5-11e9-80d5-5d6e1d84bdfe.png)

**Comment by charliesantos** [comment]
Hi @tedg ,

Thank you for reporting this. We have updated the official documentation.

Thanks,

Charlie Santos
JSDK Team
