### ISSUE TITLE
[BUG]WebSocket constant reconnect

### ISSUE THREAD

**Issue by gjones12687** [twilio/twilio-client.js#49]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

```js
$(document).ready(function(){
    token = 'omitted'
    Twilio.Device.setup(token, {debug: true});
})
```

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="jquery.js"></script>
    <title>TEST</title>
    <script src="twilio.js"></script>
    <script src="test.js"></script>
</head>

<body>
		Testing
</body>
</html>
```

**Expected behavior:**
Device should be created and websocket should connect and stay connected

**Actual behavior:**
WebSocket continuously connects and disconnects. Unless using firefox with a breakpoint on line 2587 in twilio.js, in which case when continuing the WebSocket will successfully stay connected.

I have tested this using a flask backend that generates an Access Token aswell as a static page using a pre-generated token with a ttl of 24 hours.

I have tried multiple versions of twilio.js with the same results, from both the CDN and npm.

```log
Setting up VSP twilio.1.js:5650:46
WSTransport.open() called... twilio.1.js:5650:46
Attempting to connect... twilio.1.js:5650:46
Closing and cleaning up WebSocket... twilio.1.js:5650:46
No WebSocket to clean up. twilio.1.js:5650:46
WebSocket opened successfully. twilio.1.js:5650:46
[PStream] Setting token and publishing listen twilio.1.js:2878:21
Closing and cleaning up WebSocket... twilio.1.js:5650:46
Will attempt to reconnect WebSocket in 133ms twilio.1.js:5650:46
Stream is offline twilio.1.js:5650:46
Attempting to reconnect (retry #1)... twilio.1.js:5650:46
Closing and cleaning up WebSocket... twilio.1.js:5650:46
No WebSocket to clean up. twilio.1.js:5650:46
WebSocket opened successfully. twilio.1.js:5650:46
[PStream] Setting token and publishing listen twilio.1.js:2878:21
Closing and cleaning up WebSocket... twilio.1.js:5650:46
```

With firefox breakpoint:

```log
Setting up VSP twilio.1.js:5650:46
WSTransport.open() called... twilio.1.js:5650:46
Attempting to connect... twilio.1.js:5650:46
Closing and cleaning up WebSocket... twilio.1.js:5650:46
No WebSocket to clean up. twilio.1.js:5650:46
WebSocket opened successfully. twilio.1.js:5650:46
[PStream] Setting token and publishing listen
```

I have also tested on three different networks, with vastly different configurations.

**Software versions:**

 - [x] Browser(s): Google Chrome, Microsoft Edge, Chromium, Firefox - All fully updated
 - [x] Operating System: Ubuntu 18.04, Windows 10
 - [x] twilio.js: 1.7, 1.6.10, 1.4.35
 - [x] Third-party libraries (e.g., Angular, React, etc.): jquery v3.1.1, jquery v3.4.1

**Comment by gjones12687** [comment]
Found the solution to this - I was using access tokens, rather than capability tokens, which resulted in the websocket not connecting properly. Don't know why the firefox breakpoint seemed to fix this. But it may be worth either ensuring documentation states that a capability token is still needed for the twilio-client.js. Or changing everything to access tokens.

**Comment by ryan-rowland** [comment]
@gjones12687 twilio-client.js supports both AccessToken and CapabilityToken on all SDK versions you've listed here -- Perhaps there is an issue with the way the AccessToken is being created? Without posting any personal info, could you share the code you're using to generate the AccessToken?

**Comment by gjones12687** [comment]
```python
@app.route('/token', methods=['GET'])
def get_token():
    token = AccessToken(
            app.config['TWILIO_ACCOUNT_SID'], # AC*******
            app.config['TWILIO_API_SID'], # SK*******
            app.config['TWILIO_API_SECRET']
    )

    voice_grant = VoiceGrant(
            outgoing_application_sid=app.config['TWIML_APPLICATION_SID'],  # AP*******
            incoming_allow=True
    )
    token.add_grant(voice_grant)

    token = token.to_jwt()

    return jsonify({'token': token.decode("utf-8")})
```

That's the code I am using to generate the Access token.

**Comment by ryan-rowland** [comment]
@gjones12687 Is this similar logic to your Capability Token logic? I noticed you don't seem to be setting an identity on this token. I believe that might cause an issue as you try to register to listen for incoming calls.

**Comment by gjones12687** [comment]
@ryan-rowland So quick test with an identity does seem to solve the problem. Although I've just looked through the documentation again and it doesn't specify that an identity is required, although it does use an identity because it's presented through the python api as an optional argument this does make it seem like it's optional.
https://www.twilio.com/docs/iam/access-tokens?code-sample=code-creating-an-access-token-voice-2&code-language=Python&code-sdk-version=6.x
