### ISSUE TITLE
MOS score is null on Safari

### ISSUE THREAD

**Issue by mtdewulf** [twilio/twilio-client.js#70]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

On a connection object, do: `on("sample", (sample) => { console.log(JSON.stringify(sample)); })`

**Expected behavior:**

MOS score is defined.

**Actual behavior:**

MOS score is null on Safari.  Note, this works on Win10 Chrome 76.0.3809.132 just fine.  I've also used `codecPreferences` to try both codecs and have verified the MOS score is NULL with either opus and pcmu on Safari.

Output from sample (totals removed):

```JSON
{
 "bytesReceived":3621,
 "bytesSent":4175,
 "codecName":"opus",
 "jitter":0,
 "mos":null,
 "packetsLost":0,
 "packetsLostFraction":0,
 "packetsReceived":51,
 "packetsSent":52,
 "timestamp":1568403060431
}
```

Notice `mos: null` and `rtt` is missing (I'm guessing this might be related).

**Software versions:**

 - [x] Browser(s): Safari 12.1.2 (14607.3.9)
 - [x] Operating System: macOS 10.14.6
 - [x] twilio.js: 1.9.0
 - [] Third-party libraries (e.g., Angular, React, etc.): I think N/A for this one?  I can post my `package-lock.json` file, if need be.

**Comment by charliesantos** [comment]
Hi @mtdewulf 

Thank you for reporting this. We will take a look and get back to you when we have more information.

Thanks,

Charlie Santos
JSDK Team

**Comment by charliesantos** [comment]
Hi @mtdewulf , rtt is used to calculate mos. Unfortunately, that feature is currently not available in Safari.

**Comment by charliesantos** [comment]
Should be fixed on https://github.com/twilio/twilio-client.js/pull/74
We will include on a future release.
