### ISSUE TITLE
[BUG] Under certain network conditions, audio in dialer fails

### ISSUE THREAD

**Issue by bryandbs** [twilio/twilio-client.js#71]
- [ X ] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [ X ] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ X ] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [ X ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

The issue we're facing is that some of our clients are using our application behind corporate proxies or behind restrictive firewalls.  We can recreate the issue locally by blocking UPD connections on port range 10,000 - 20,000.  The twilio network test tool also fails under these conditions. 

This is all understandable, the problem is that the dialer and connection both throw no error and we have no way of detecting this problem to direct our users appropriately.  The call simply completes and no audio is heard by either side.  This is all around unacceptable user experience, the only work around we can figure right now is detecting a lack of audio from the connection for a certain time period

**Expected behavior:**

Ideally, the connection or device would throw some kind of error letting us know what's going on.

**Actual behavior:**

The device and connection both seem to have no idea anything is wrong but the call drops after some period of time.

**Software versions:**

 - [ ] Browser(s):  N/A
 - [ ] Operating System:  N/A
 - [ ] twilio.js: Latest
 - [ ] Third-party libraries (e.g., Angular, React, etc.):  N/A

**Comment by charliesantos** [comment]
Hi @bryandbs ,

Thank you for reporting this.
This type of error is currently reported as a Media Connection error which happens when media connection fails.
Please see change log here https://www.twilio.com/docs/voice/client/javascript/changelog#media-reconnection-states-and-events

Event emitted when this happens: https://www.twilio.com/docs/voice/client/javascript/connection#onreconnecting-handlererror

Event emitted when connection is recovered: https://www.twilio.com/docs/voice/client/javascript/connection#onreconnected-handler

Thank you,
Charlie

**Comment by bryandbs** [comment]
I appreciate the feedback. But then maybe the bug here is that this error doesn't seem to be emitting? I've added this handler:

`    
  connection.on('reconnecting', (e: any) => {
      console.log(e);
    });
`
and I'm still seeing nothing emit.  I'e also got the standard connection error handler and the device error handler listening.

**Comment by charliesantos** [comment]
What are your options on `device.setup(token, options)`? Can you also provide me a Call Sid that I can take a look at?

**Comment by ryan-rowland** [comment]
@bryandbs The functionality was added recently (in 1.8.0) behind a flag because technically it's a breaking change. The flag is `enableIceRestart`, eg
```
Device.setup(token, { enableIceRestart: true });
```
```

**Comment by charliesantos** [comment]
Please see above comments for resolution.
