### ISSUE TITLE
[BUG] When RTT is > 1000 returned MOS raises instead of lowers.

### ISSUE THREAD

**Issue by highway900** [twilio/twilio-client.js#75]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

A stock v1.7 quickstart twilio client will present this issue

**Expected behavior:**

MOS should stop at 1.0 if lower than 1

**Actual behavior:**

![image](https://user-images.githubusercontent.com/1100256/65207664-abfec300-dad5-11e9-84ea-edb53589744a.png)

**Software versions:**

 - [x] Browser(s): 76.0.3809.132
 - [x] Operating System: OSX 10.14.6
 - [x] twilio.js: v1.7
 - [x] Third-party libraries (e.g., Angular, React, etc.): None

**Comment by ryan-rowland** [comment]
Thanks for reporting, @highway900 . We have similar reports in Mobile and will be looking into the root cause.

**Comment by ryan-rowland** [comment]
As an update, we've verified the issue and have found the root cause in the current algorithm, and are currently investigating changing the algorithm.

**Comment by highway900** [comment]
@ryan-rowland any change WRT this issue?
