### ISSUE TITLE
[FEATURE] Detection if call went to voicemail

### ISSUE THREAD

**Issue by thomas-jeepe** [twilio/twilio-client.js#82]
I want to be able to automatically add a record (from the javascript client) after a call, recording the length of the call, whether or not the contact answered the phone and any notes the user wants to add.

All the features I listed are possible except detecting whether or not the contact answered the call. As of right now if the contact answered or if the call went to voicemail, the same events are fired, meaning I don't have any way to detect if the contact was answered.

**Comment by ryan-rowland** [comment]
Hi @thomas-jeepe, thanks for the feedback! Twilio does offer [Answering Machine Detection](https://www.twilio.com/docs/voice/answering-machine-detection), which you can interact with through a webhook (see link for details). We currently don't have REST events and webhooks being piped through to the SDK, but it's something we think would be beneficial and is something we'd like to tackle. Unfortunately, I can't attest to the time frame at this point.
