### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by ismailmohammed** [twilio/twilio-client.js#84]
**Text to Speech in client side**
Hi All,

Please help me on developing twilio client for Text-to-speech. where user will type the text in text box an clicks on play.

I have followed below link and changed my code as below,
[https://www.twilio.com/blog/2011/08/testing-twilios-text-to-speech-engine-using-twilio-client.html](url)

 `
[twilio-TextToSpeech.txt](https://github.com/twilio/twilio-client.js/files/3728792/twilio-TextToSpeech.txt)
`

But I'm getting below error,
 "Audiohelper, pstream and getUserMedia are required arguments"

Thanks in advance,
Md.Ismail

**Comment by mdovn** [comment]
![image](https://user-images.githubusercontent.com/58581558/72267342-7d8f8f80-3652-11ea-9625-df420b4d0fa6.png)
I have this problem too. It's so annoying

**Comment by charliesantos** [comment]
Hi @ismailmohammed and @mdovn , thank you for the report. We recommend submitting a ticket at support@twilio.com or through your Twilio Console. Our support will be more than happy to help resolve this. Feel free to link to this issue to provide our support team with more context.
